In [4]:
import numpy as np
arr= np.array([1,2,3,4,5])
print("hello numpy")
print(arr)

hello numpy
[1 2 3 4 5]


In [5]:
arr1= np.zeros([3,4])
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
arr2= np.ones([2,3])
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr3 = np.full([4,6], 2.3)# [rows, columns], default value
print(arr3)

[[2.3 2.3 2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3 2.3 2.3]
 [2.3 2.3 2.3 2.3 2.3 2.3]]


In [8]:
arr4 = np.random.rand(2,3)# it provide random number b/w 0 & #1
print(arr4)

[[0.74010802 0.11114636 0.01354231]
 [0.20449599 0.06705838 0.78775147]]


In [9]:
arr5= np.random.randn(2,3)  # it will provide random number #weather minus aur plus b/w 0 & 1
print(arr5)

[[-0.85740522 -0.89023723 -0.85116976]
 [-0.35524754  0.94003429  1.13257671]]


In [10]:
arr6= np.random.randint(2,484)# in these we are giving range #as input to machine print any ramdom number b/w 2 & 3
print(arr6)

74


In [11]:
#Numpy datatypes and typecasting
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
                [11,12,13,14,15]])
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
print(len(arr))

3


In [14]:
arr.dtype

dtype('int64')

In [15]:
arr.ndim

2

In [16]:
arr.size

15

In [17]:
arr.shape

(3, 5)

In [18]:
arr.itemsize

8

In [19]:
import numpy as np
arr7= np.array([1,2,3,4,5,6])
reshaped= arr7.reshape(2,3)
print(reshaped)
reshaped2= reshaped.reshape(3,2)
print(reshaped2)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
ravel = reshaped2.ravel()
ravel[0]= 29
print(ravel)
print(reshaped2)

[29  2  3  4  5  6]
[[29  2]
 [ 3  4]
 [ 5  6]]


In [21]:
flat= reshaped2.flatten()
flat[0]=10
print(flat)
print(reshaped)

[10  2  3  4  5  6]
[[29  2  3]
 [ 4  5  6]]


In [22]:
# Arithmatic operations
# Addition
a= np.array([1,2,3,4,5])
b=np.array([2,3,4,5,5])

print(a+b)

[ 3  5  7  9 10]


In [23]:
print(a-b)

[-1 -1 -1 -1  0]


In [5]:
import numpy as np
# indexing and Slicing

lss=np.array([1,2,3,4,5,6])
print(lss[0])
print(lss[1:])
print(lss[0:3])

1
[2 3 4 5 6]
[1 2 3]


In [3]:
#matrixing
import numpy as np
mat=np.array([[1,2,3,4],
             [5,6,7,8],
             [1,0,3,6]])
print(mat[1:, 2:])

[[7 8]
 [3 6]]


In [ ]:
import django as dj
qldk